# Generated by Django 4.2.1 on 2023-06-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaProducto',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de producto')),
                ('nombreProducto', models.CharField(blank=True, max_length=50, verbose_name='Nombre de producto')),
                ('descripcionProducto', models.CharField(blank=True, max_length=50, verbose_name='Descripcion de producto')),
                ('precioProducto', models.IntegerField(blank=True, verbose_name='Precio de producto')),
                ('imagenProducto', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen de producto')),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.categoriaproducto')),
            ],
        ),
    ]
