# Generated by Django 4.2.1 on 2023-06-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockProducto',
            field=models.IntegerField(blank=True, default=1, verbose_name='Stock de producto'),
            preserve_default=False,
        ),
    ]
