# Generated by Django 4.2.1 on 2023-07-02 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_producto_stockproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de boleta')),
                ('fechaBoleta', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de boleta')),
                ('totalBoleta', models.BigIntegerField(verbose_name='Total de boleta')),
                ('idCliente', models.IntegerField(blank=True, verbose_name='ID de cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('idDetalleBoleta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de detalle de boleta')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de producto')),
                ('subtotal', models.BigIntegerField(verbose_name='Subtotal de producto')),
                ('idBoleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.boleta', verbose_name='ID de boleta')),
                ('idProducto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.producto', verbose_name='ID de producto')),
            ],
        ),
    ]
