# Generated by Django 4.2.1 on 2023-07-02 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascotas', '0003_boleta_detalleboleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID de cliente'),
        ),
    ]
